apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: atlas-claim1
  name: atlas-claim1
  namespace: atlas-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
