apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: scb-frontend
  namespace: scb-frontend
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - scb-frontend.c-77b2870.kyma.ondemand.com
  service:
    name: scb-frontend
    port: 80
  rules:
  - path: /api
    methods:
    - GET
    - HEAD
    - OPTIONS
    - POST
    - PUT
    - DELETE
    - PATCH
    noAuth: true
    service:
      name: catalog-api
      port: 8000
  - path: /
    methods:
    - GET
    - HEAD
    - OPTIONS
    - POST
    - PUT
    - DELETE
    - PATCH
    noAuth: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: scb-frontend-config
  namespace: scb-frontend
data:
  API_BASE_URL: "/api"
  NODE_ENV: "production"
