

CATEGORY_SOURCE_ALIGNED = "Source Aligned"
CATEGORY_INTERMEDIATE = "Intermediate"
CATEGORY_CONSUMER_ALIGNED = "Consumer Aligned"
LABEL_DATA_PRODUCT_CATEGORY = [
    CATEGORY_SOURCE_ALIGNED, CATEGORY_INTERMEDIATE, CATEGORY_CONSUMER_ALIGNED
]